version: "3.8"
services:
  backend:
    image: "lauretsdev/springboot-react-fullstack:10.4.2021.6.42.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev